### ISSUE TITLE
Garden, bot not switching soil type after ascension and unlocking new soils

### ISSUE THREAD

**Issue by BiscuitCookies** [prinzstani/CookieBot#103]
After my first ascension and reaching fertilizer again the bot didn't switch to it. I waited multiple ticks to see if it switched.
It is trying for bakeberries and looking at the bot code it should be using fertilizer for that, instead it stays on dirt.

it also seemed to have switched back to dirt after I manually set it to fertilizer at some point.

**Comment by prinzstani** [comment]
This seems perfectly correct to me.
The bot uses fertilizer when a new plant is growing for the first time in order to get to its seed faster.
When the bot is waiting for the new plant, then it uses woodchips to have more mutations.
If woodchips are not unlocked, it uses dirt.
When the bot is trying to get bakeberry cookies, then it plants bakeberries with fertilizer in order to harvest them earlier.

If you still think it is a bug, please provide an export save.

**Comment by BiscuitCookies** [comment]
Ah, I assumed the faster ticks means more often a check for appearance of bakeberries, bit I guess it is not?

**Comment by prinzstani** [comment]
No, the bot checks once a minute for changes independent of the kind of soil.

**Comment by BiscuitCookies** [comment]
No, didn't mean the bot, but the game.

**Comment by prinzstani** [comment]
Oh, I see. Yes, it might be an advantage to use the fertilizer as long as the woodchips are not available.
This is not currently implemented, but could be a small improvement.

**Comment by Kikithecat12345** [comment]
The garden strategy should probably be updated anyway, the potential for added CPS when the garden is finished is quite high. Whether or not this will actually help once the garden is finished is debatable but it is still worth considering IMO.

**Comment by PrinzAndreas** [comment]
Sure, if you have concrete proposals, put them here. I do not work on this problem in the next few weeks.

**Comment by Kikithecat12345** [comment]
A potential change that might be worth looking into is, once all sugar lumps are acquired, we can instead focus on using the passive effects of the plants to their advantage. (see [wiki](https://cookieclicker.wiki.gg/wiki/Garden#Species_Details))  

Of particular note is the following plants: 
- Golden Clovers, which each increase the frequency of Golden Cookies by +3%
- Nursetulip, which boost the effect of nearby plants (3x3) by +20% at the cost of -2% CPS (worth it for clovers)
  - It's worth noting that the CPS debuff can be ignored by uprooting the plant, as the buff sticks around for 1 garden tick. This means we can have a huge buff in golden cookie spawns without any debuff as long as every tick we plant and then immediately uproot the Nursetulips. We can even plant other plants in it's place, but the cost of those plants need to be carefully considered. 
  - The optimal Golden Clover/Nursetulip strategies are on the [Wiki.](https://cookieclicker.wiki.gg/wiki/Garden_Strategies#Golden_Clover)
 - Late-game, Whiskerbloom boosts CPS the most by boosting milk.

#102 should be fixed as when this proposal is implemented, otherwise the strategy will not work. 

That being said, this issue itself is a simple fix.
