### ISSUE TITLE
Chocolate egg question

### ISSUE THREAD

**Issue by Dabrinka** [prinzstani/CookieBot#11]
It could be that I'm impatient, but it seems like the bot doesn't want to buy the chocolate egg upgrade. The wrinklers are left alone. The garden is being played as normal and if enough cookies are in the bank, buildings will be bought, but the Chocolate Egg upgrade and elder pact is not bought.

So my question is: Is the bot waiting or is it stuck?

Attaching the save file.

[CC_Dab_Bot.txt](https://github.com/prinzstani/CookieBot/files/2023912/CC_Dab_Bot.txt)

**Comment by zvei** [comment]
@Dabrinko 
The chocolate eggs and wrinklers work so that the longer you leave them the more efficient they are. Technically it's waiting till your next xx cookies baked in one ascension achievement then it'll buy the chocolate egg and pop the wrinklers and ascend. Likewise you can just buy or pop them yourself if your impatient but the bot will wait. I hope this helps

**Comment by Dabrinka** [comment]
Thanks for the answer! Just have to be patient, then.
