### ISSUE TITLE
Bot trying to mutate Juicy Queenbeet on a tile where Everdaisy is still in sprout

### ISSUE THREAD

**Issue by PeterRed4091** [prinzstani/CookieBot#24]
Spotted in Cookie Clicker v2.016 beta, with Cookie Bot v2.016 beta
The garden size was 6x5 (stage 8/9), and the bot seemed to be failing to check if a plant is already growing on the mutation spot.
Bot noticed "Everdaisy is still growing" but still "Trying to get plant Juicy queenbeet" on that sector.
Attached is a save file for your convenience.
[AutomatedPeterRedBakery.txt](https://github.com/prinzstani/CookieBot/files/2729229/AutomatedPeterRedBakery.txt)

**Comment by prinzstani** [comment]
That is a feature, not a bug. Whenever a plant is mutated, the bot is moving on to the next plant. Still, it makes sure that the mutated plant is not removed. Admittedly, in your situation, this seems a bit odd, because the queenbeet will be gone before the the everdaisy is ripe, but normally it works fine, and there no harm in planting queenbeet.
