### ISSUE TITLE
Suggestion: Show what the bot is doing

### ISSUE THREAD

**Issue by Bediko** [prinzstani/CookieBot#3]
Hi there, I would like to suggest that the bot shows somewhere what he is doing next/waiting for, so users get more insight what is going on

**Comment by prinzstani** [comment]
Very good idea. For the moment, cookie bot creates a (short-lived) note about what it is doing and waiting for. You can get this note again by reloading cookie bot.

**Comment by BujuArena** [comment]
The bot appears to stop working periodically.  I'm not sure when or why, because I come back once every day or so and it's randomly either working or not working.  I reload it via the bookmarklet and it tells me it's working on earning 100 undecillion cookies, but that doesn't mean it should stop clicking and buying stuff.  It doesn't start working when I reload it.  It just starts working eventually when I come back and check it again later or the next day.

**Comment by BujuArena** [comment]
This has been a problem since before the 2.0045 update.

**Comment by prinzstani** [comment]
Interesting. Can you provide me with a save of your game that I can have a look?
Maybe the bot tries to get the neverclick and/or hardcore achievements. This is done in endgame, i.e. when you have already most of the other achievements. When you then click, you destroy the possibility to get the neverclick, and it will retry after the next ascend.

**Comment by BujuArena** [comment]
[AlexCookiemachineBakery.txt](https://github.com/prinzstani/CookieBot/files/1777803/AlexCookiemachineBakery.txt)

Here's my save.  It was working the last time I checked, so I hope you can reproduce the issue.

**Comment by prinzstani** [comment]
Everything works fine here with me, so I cannot find a problem.
However, maybe you missed the following feature of cookiebot: The tool is designed to mimic a human player, and it avoids being super-human in terms of clicking speed and possible moves. This includes also not playing at night, i.e. from 23:00 until 07:00. For the night mode, if possible, the golden switch is used together with fitting spirits in order to maximize output.
That means that the bot is never working between 23:00 and 07:00. So if you check in during this time, it is completely normal that it does not work. This is a feature.
Still, the nightmode should be shown ans also there should be a possibility to switch on and off nightmode, see also #1

**Comment by BujuArena** [comment]
You were right.  I didn't know about it turning off during certain hours of the day.  I don't personally follow that particular schedule, so I often saw it seemingly inexplicably off.  Thanks for the explanation!

**Comment by prinzstani** [comment]
Now the bot is showing its activity when you hover over the version information (bottom left of game screen).

**Comment by BujuArena** [comment]
Nice.  Thanks!  I forked the bot, turned off night mode, and made some things run with 17 ms intervals.  It uses a bit more CPU, but it feels a lot better to me now, especially in those cookie storms.  It can actually click all the cookies and click really fast.  Thank you so much for writing it!
