### ISSUE TITLE
Improve Lucky Payout strategy

### ISSUE THREAD

**Issue by frozenca** [prinzstani/CookieBot#58]
The bot behavior becomes annoying when it try to get lucky payout,
because it has poor strategy to match prestige level ending to 777777.
No interval calculation, no selling buildings to slower CpS.
It loops so many time, so please remove that part,
or improve the strategy to slow down CpS to match prestige level ending in a single run,
or at least give a way to toggle the strategy.

**Comment by prinzstani** [comment]
From the FAQ: What is the strategy for lucky payout upgrade?
In order to exactly match the 777777 for the lucky payout, the bot only goes to half the distance. So if starting from 333333, it will only go to 555555 and then ascend. From 555555, it will ascend at 666666. This makes it uncritical to go too high, as there is typically plenty of space left. This approach ensures that the bot can get single prestige levels when it gets close to 777777. However, when the prestige level is too high, the precision of prestige makes it impossible to achieve single steps. In this case, the bot goes as close to 777777 as possible and the cheats the upgrade.

This strategy worked for all the cases that I have tried and it is far from random. It might be improved in terms of speed, but it will get to 777777 with at most 20 ascensions. The bot does not sell buildings, it just does an ascend when it comes too close to the limit. This is most compatible with the rest of the workings of the bot.

Please provide an export save of your situation such that I can have a look.

**Comment by prinzstani** [comment]
It might be possible to introduce a lucky payout strategy which only needs one ascend, but this is a bigger change. Could be a future improvement.

**Comment by prinzstani** [comment]
fixed with stable now
