### ISSUE TITLE
Buy upgrades in early-game.

### ISSUE THREAD

**Issue by 0x2640** [prinzstani/CookieBot#86]
Currently, Cookiebot waits to buy upgrades at the beginning of the game until it gets all the golden cookie upgrades. This should be changed as it severely hinders the number of cookies you make. I'm assuming this is just behavior and not a bug.

**Comment by prinzstani** [comment]
I am not sure I understand the problem.
The bot does not wait with buying upgrades, but it does buy buildings before upgrades.
There is also a general waiting period of one minute whenever the bot is idle.
Where are you at the beginning of the game? What is the current main objective of the bot?
Can you provide an export save of the situation?

**Comment by 0x2640** [comment]
Here is an export save of the game. It is a full cookiebot run from the very beginning, and as you can see it has still not bought any upgrades. It's currently trying to declare a covenant with the grandmatriarchs and get the hardcore achievement. It is not saving until golden cookie upgrades, but those don't turn up until around 777 million cookies in.

[eyaBakery (1).txt](https://github.com/prinzstani/CookieBot/files/9800544/eyaBakery.1.txt)

**Comment by 0x2640** [comment]
Basically, the issue is it waits to buy any upgrades until it has enough for the golden cookie upgrades, I'm assuming this isn't intended behavior (and it basically makes it take days longer to get to the golden cookie upgrades)

**Comment by prinzstani** [comment]
I see. The hardcore achievement that the bot is trying to get is the following:
Achievement hardcore (ID: 92): Get to 1 billion cookies baked with no upgrades purchased.
This is the reason that the bot does not buy any upgrades because it would spoil the hardcore achievement.

Just wait until you reach 1 billion cookies, then the bot will buy all available upgrades.
This is a feature, not a bug.
