### ISSUE TITLE
Game is not loaded yet, waiting ...

### ISSUE THREAD

**Issue by 0x2640** [prinzstani/CookieBot#89]
Brand new save on the official website, bot keeps saying the game hasn't loaded in.
Edit: Using beta, not stable
![image](https://user-images.githubusercontent.com/66527398/216781518-fd66f210-9f3e-48f5-9282-8b9a84d06beb.png)

**Comment by 0x2640** [comment]
This fixes itself if you just click the cookie once, but then you can't get the True Neverclick achievement.

**Comment by prinzstani** [comment]
Yes, this is because it is difficult to find out whether the game is loaded or not. Currently, we check for the first achievement to be present, which is not when you start a new one.
Two options around:
1) Use the stable (not the beta).
2) click some cookies, load the bot, and wipe save to start fresh

**Comment by 0x2640** [comment]
Maybe check for the name achievement? Most people will get it shortly after starting a playthrough.

**Comment by prinzstani** [comment]
The trouble is that the bot should be able to start from a clean state where NOTHING is yet done.
Finding any won achievement is not possible in this situation.
The right way to do it is to wait some time and then just start the bot.

**Comment by Kikithecat12345** [comment]
Maybe we can check if it's a new save? If it's a new save, wait 5-10 seconds, then start the bot. (to make sure it's loaded)
Another thing to consider is if there is a way to hook into the existing start routine with a callback to the main loop of the bot. If there is, we could use that instead.

**Comment by prinzstani** [comment]
I probably should mention that this is related to [issue 79](https://github.com/prinzstani/CookieBot/issues/79).
We want the bot to wait until the game is finally loaded.
One would hope that this is indicated by Game.ready, but it is not.
So I check whether Achievement 0 is won yet, which is not the case in a blank game.
Actually, there is nothing I can see that we can check to distinguish a blank game from a game that is not loaded yet.
Maybe it is possible to check whether Game.Achievements is non-empty.
Anyway, my current plan is to delay the start of the bot only 3-5 times with increasing intervals (i.e. 10-20 seconds).
If this is a clean game, 20 seconds should be no problem. If this is an existing game, it will have started now.

I have also checked the MODDING API, but it is also relying on Game.ready.

**Comment by Kikithecat12345** [comment]
A blank save will (besides the name bytes) always show the same pattern. If you set the name to something known, then get the exported save, we can check against a blank save with the same name. We can then set the name back, and start the bot based on that.

**Comment by prinzstani** [comment]
That seems possible. I tried to avoid looking into the save because it seems like quite some work.
I consider this a minor problem, as it only happens when the bot is started from scratch.
My solution would still be to restrict the length of the waiting, which seems simple enough.
BTW, the problem only happens with the beta bot.

**Comment by prinzstani** [comment]
new fixed with stable release
